#
# Module manifest for module 'BusBuddy'
#
# Generated by: Bus Buddy Development Team
#
# Generated on: $(Get-Date)
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'BusBuddy.psm1'

    # Version number of this module.
    ModuleVersion        = '1.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID                 = '12345678-1234-5678-9012-123456789012'

    # Author of this module
    Author               = 'Bus Buddy Development Team'

    # Company or vendor of this module
    CompanyName          = 'Bus Buddy Project'

    # Copyright statement for this module
    Copyright            = '(c) 2025 Bus Buddy Project. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Professional PowerShell module optimized for PowerShell 7.5+ and Bus Buddy WPF development. Features enhanced JSON handling, performance optimizations, structured error reporting, and comprehensive development workflow automation with motivational developer happiness features.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '7.5'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the root module
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Get-BusBuddyProjectRoot',
        'Write-BusBuddyStatus',
        'Write-BusBuddyError',
        'Test-BusBuddyConfiguration',
        'Test-BusBuddyEnvironment',
        'Test-PowerShell75Features',
        'Invoke-BusBuddyBuild',
        'Invoke-BusBuddyRun',
        'Invoke-BusBuddyTest',
        'Invoke-BusBuddyClean',
        'Invoke-BusBuddyRestore',
        'Start-BusBuddyDevSession',
        'Invoke-BusBuddyHealthCheck',
        'Get-BusBuddyHappiness',
        'Get-BusBuddyCommands',
        'Get-BusBuddyInfo'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @(
        'bb-build',
        'bb-run',
        'bb-test',
        'bb-clean',
        'bb-restore',
        'bb-dev-session',
        'bb-health',
        'bb-env-check',
        'bb-happiness',
        'bb-commands',
        'bb-info'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList             = @(
        'BusBuddy.psm1',
        'BusBuddy.psd1',
        'README.md'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('BusBuddy', 'WPF', 'Development', 'Build', 'Automation', 'Transportation', 'CSharp', 'DotNet')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/Bigessfour/BusBuddy-WPF/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/Bigessfour/BusBuddy-WPF'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @"
Version 1.0.0
=============

Initial release of the Bus Buddy PowerShell Module.

Features:
- Professional PowerShell module structure for development workflow
- Build automation (bb-build, bb-run, bb-test, bb-clean, bb-restore)
- Development session management (bb-dev-session, bb-health)
- Environment validation (bb-env-check)
- Developer happiness quotes (bb-happiness)
- Comprehensive command discovery (bb-commands, bb-info)
- Industry-standard module organization with proper exports

Requirements:
- PowerShell 7.0+
- .NET 8.0+
- Bus Buddy WPF project structure

Quick Start:
1. Import-Module .\PowerShell\BusBuddy.psm1
2. bb-dev-session (starts complete development environment)
3. bb-happiness (because you deserve motivation!)
"@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
